name: kubernetes

on: 
  workflow_call

jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{secrets.ID_CHAVE_ACESSO}}
       aws-secret-access-key: ${{secrets.CHAVE_SECRETA}}
       aws-region: us-east-2
        
 
    - uses: actions/checkout@v3
      with:
        repository: thaysesf/Infra_CI_Kubernetes
        path: terraform

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: ls

    - run: terraform -chdir=terraform/env/Homolog init

    - run: terraform -chdir=terraform/env/Homolog apply -auto-approve

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - run: aws sts get-caller-identity 

    - run: aws eks update-kubeconfig --region us-east-2 --name eks-app-go
    
    - run: ls
    
    - run: kubectl apply -f deployment.yaml
